<?php

//--include_once "MdlHistoriData.php";
class MdlPostalCodes extends MdlMother
{

    protected $tableName = "postal_codes";
    protected $indexFields = "id";


    protected $listedFieldsForm = array();
    protected $listedFieldsHidden = array();
    protected $search;
    // protected $filters = array("jenis='profile'", "extern_type='company'", "status='1'", "trash='0'");
    protected $sortBy = array(
        // "kolom" => "alias",
        // "mode"  => "ASC",
    );

    protected $validationRules = array(

        "tlp_1"     => array("required", "numberOnly"),
        "no_ktp"    => array("required", "numberOnly"),
        "nama"      => array("required"),
        "npwp"      => array("required"),
        "status"    => array("required"),
        "tlp"       => array("required"),
        "alamat"    => array("required"),
        "kabupaten" => array("required"),
        "propinsi"  => array("required"),
    );

    protected $listedFieldsView = array("nama");
    protected $fields = array(
        "id"       => array(
            "label"     => "id",
            "type"      => "int", "length" => "24", "kolom" => "id",
            "inputType" => "hidden",// hidden
            //--"inputName" => "id",
        ),

    );
    protected $listedFields = array(
//        "extern_id" => "company",
        "kecamatan" => "kecamatan",
        "kabupaten" => "kabupaten",
        "propinsi"  => "propinsi",
    );

    function __construct()
    {
        parent::__construct();
    }

    public function getTableName()
    {
        return $this->tableName;
    }

    public function setTableName($tableName)
    {
        $this->tableName = $tableName;
    }

    public function getIndexFields()
    {
        return $this->indexFields;
    }

    public function setIndexFields($indexFields)
    {
        $this->indexFields = $indexFields;
    }

    public function getListedFieldsForm()
    {
        return $this->listedFieldsForm;
    }

    public function setListedFieldsForm($listedFieldsForm)
    {
        $this->listedFieldsForm = $listedFieldsForm;
    }

    public function getListedFieldsHidden()
    {
        return $this->listedFieldsHidden;
    }

    public function setListedFieldsHidden($listedFieldsHidden)
    {
        $this->listedFieldsHidden = $listedFieldsHidden;
    }

    public function getSearch()
    {
        return $this->search;
    }

    public function setSearch($search)
    {
        $this->search = $search;
    }

    public function getFilters()
    {
        return $this->filters;
    }

    public function setFilters($filters)
    {
        $this->filters = $filters;
    }

    public function getValidationRules()
    {
        return $this->validationRules;
    }

    public function setValidationRules($validationRules)
    {
        $this->validationRules = $validationRules;
    }

    public function getListedFieldsView()
    {
        return $this->listedFieldsView;
    }

    public function setListedFieldsView($listedFieldsView)
    {
        $this->listedFieldsView = $listedFieldsView;
    }

    public function getFields()
    {
        return $this->fields;
    }

    public function setFields($fields)
    {
        $this->fields = $fields;
    }

    public function getListedFields()
    {
        return $this->listedFields;
    }

    public function setListedFields($listedFields)
    {
        $this->listedFields = $listedFields;
    }

    public function callDatas()
    {
//        $cabang_id = isset($this->cabang_id) ? $this->cabang_id : matiDisini("cabang_id harap diset dulu" . __METHOD__);

        $condites = array(
            "main_used" => 0,
        );
        $src = $this->lookupByCondition($condites)->row();

        return $src;
    }

    public function updateDataPreparation($kolom_data)
    {
//    arrPrint($_SESSION);
//        $toko_id = isset($this->toko_id) ? $this->toko_id : matiDisini("tokoo_id harap diset dulu" . __METHOD__);
        $where = array(
            "extern_type" => "company",
        );
        $data = array(
            $kolom_data . "_ok" => 1,
            $kolom_data . "_dtime" => dtimeNow(),
        );

        return parent::updateData($where, $data); // TODO: Change the autogenerated stub
    }

    public function insert_batch($data) {
        $this->db->insert_batch($this->tableName, $data);
    }

    public function getPropinsi(){
        $this->db->group_by("propinsi_id");
        $query = $this->lookupAll();

        $this->indexFields = "propinsi_id";
        $this->indexFields = "propinsi";

        return $query;
    }

    public function getKabupaten(){

        $filters = [
            "propinsi_id" => 14
        ];
        $this->db->where($filters);
        $this->db->group_by("kabupaten_id");
        $query = $this->lookupAll();

        $this->indexFields = "kabupaten_id";
        return $query;
    }

    public function getKecamatan(){
        $filters = [
            "kabupaten_id" => 14
        ];
        $this->db->where($filters);
        $this->db->group_by("kecamatan_id");
        $query = $this->lookupAll();

        $this->indexFields = "kecamatan_id";
        return $query;
    }

    public function getKelurahan(){
        $filters = [
            "kecamatan_id" => 14
        ];
        $this->db->where($filters);
        $this->db->group_by("kelurahan_id");
        $query = $this->lookupAll();

        $this->indexFields = "kelurahan_id";
        return $query;
    }



}